import { Fragment } from "react";
import Head from "next/head";
function DefaultLayout({ children }) {
  return (
    <Fragment>
      <Head>
        <title>Công ty TNHH phần mềm HiCAS | HiCAS software company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_hicas.png" />
      </Head>

      <div>
        <div>{children}</div>
      </div>
    </Fragment>
  );
}

export default DefaultLayout;
