import Header from "../../header";
import Footer from "../../footer";
import { Fragment } from "react";
import Head from "next/head";
function DefaultLayout({ children }) {
  return (
    <Fragment>
      <Head>
        <title>HiCas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <div>{children}</div>
      </div>
      <Footer />
    </Fragment>
  );
}

export default DefaultLayout;
